#!/usr/bin/with-contenv bash
echo "Starting File Browser manager..."
# Escucha en el puerto 9090 interno
exec s6-setuidgid plex filebrowser -p 9090 -a 0.0.0.0 -r /data --noauth --database /config/filebrowser.db
